version: '3'

services:
  main:
    build: ./StarNaviProject
    ports:
      - "8000:8000"
    env_file:
      - ./StarNaviProject/.env
    depends_on:
      - main_db

  main_db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    env_file:
      - ./StarNaviProject/.env
    volumes:
      - mysql_main:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    links:
      - main_db

volumes:
  mysql_main: